import type {
  CommercialLeadStatus,
  CommercialRequirementType,
  CommercialTemplateChannel,
  DispatchCommercialCommunicationInput,
} from './types';

export const DEFAULT_STAGE_REQUIREMENTS: Array<{
  stage: CommercialLeadStatus;
  requirementKey: string;
  requirementType: CommercialRequirementType;
  config: Record<string, unknown>;
  isRequired: boolean;
  profileKey?: string;
}> = [
  {
    stage: 'primeiro_contato',
    requirementKey: 'lead.contact_available',
    requirementType: 'field',
    config: { mode: 'contact_any' },
    isRequired: true,
  },
  {
    stage: 'primeiro_contato',
    requirementKey: 'lead.pre_qualification',
    requirementType: 'boolean',
    config: { source: 'dor01_ok' },
    isRequired: true,
  },
  {
    stage: 'diagnostico_agendado',
    requirementKey: 'lead.meeting_confirmed',
    requirementType: 'event',
    config: { eventType: 'calendar:meeting_scheduled' },
    isRequired: true,
  },
  {
    stage: 'diagnostico_concluido',
    requirementKey: 'lead.diagnostic_summary',
    requirementType: 'field',
    config: { mode: 'observacao_min_length', min: 10 },
    isRequired: true,
  },
  {
    stage: 'proposta_enviada',
    requirementKey: 'lead.briefing_submitted',
    requirementType: 'field',
    config: { field: 'form_type', equals: 'briefing' },
    isRequired: true,
  },
  {
    stage: 'proposta_enviada',
    requirementKey: 'lead.lgpd_consent',
    requirementType: 'boolean',
    config: { source: 'consent_given' },
    isRequired: true,
  },
  {
    stage: 'proposta_enviada',
    requirementKey: 'lead.proposal_asset',
    requirementType: 'file',
    config: { assetType: 'proposal' },
    isRequired: true,
  },
  {
    stage: 'negociacao',
    requirementKey: 'lead.negotiation_history',
    requirementType: 'field',
    config: { mode: 'followup_any' },
    isRequired: true,
  },
  {
    stage: 'negociacao',
    requirementKey: 'lead.contract_sent',
    requirementType: 'file',
    config: { assetType: 'contract' },
    isRequired: true,
  },
  {
    stage: 'fechado',
    requirementKey: 'lead.contract_signed',
    requirementType: 'boolean',
    config: { source: 'contract_status', equals: 'assinado' },
    isRequired: true,
  },
  {
    stage: 'fechado',
    requirementKey: 'lead.payment_paid',
    requirementType: 'boolean',
    config: { source: 'payment_status', equals: 'pago' },
    isRequired: true,
  },
];

export const DEFAULT_TEMPLATE_DEFINITIONS: Array<{
  channel: CommercialTemplateChannel;
  stage: DispatchCommercialCommunicationInput['stage'];
  slug: string;
  name: string;
  content: Record<string, unknown>;
  bindAsDefault?: boolean;
}> = [
  {
    channel: 'whatsapp',
    stage: 'primeiro_contato',
    slug: 'wa_lead_qualificado_v1',
    name: 'WhatsApp Primeiro Contato',
    content: { templateKey: 'wa_lead_qualificado_v1' },
    bindAsDefault: true,
  },
  {
    channel: 'whatsapp',
    stage: 'diagnostico_agendado',
    slug: 'wa_briefing_recebido_agendamento_link_v1',
    name: 'WhatsApp Briefing Recebido + Link Agenda',
    content: { templateKey: 'wa_briefing_recebido_agendamento_link_v1' },
    bindAsDefault: true,
  },
  {
    channel: 'whatsapp',
    stage: 'diagnostico_agendado',
    slug: 'wa_briefing_recebido_agendamento_google_sugestoes_v1',
    name: 'WhatsApp Briefing Recebido + Sugestões Google',
    content: { templateKey: 'wa_briefing_recebido_agendamento_google_sugestoes_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'whatsapp',
    stage: 'diagnostico_agendado',
    slug: 'wa_briefing_recebido_agendamento_google_botoes_v1',
    name: 'WhatsApp Briefing Recebido + Botões 3 opções',
    content: { templateKey: 'wa_briefing_recebido_agendamento_google_botoes_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'whatsapp',
    stage: 'diagnostico_agendado',
    slug: 'wa_agendamento_abrir_calendario_v1',
    name: 'WhatsApp Abrir Calendário',
    content: { templateKey: 'wa_agendamento_abrir_calendario_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'whatsapp',
    stage: 'diagnostico_agendado',
    slug: 'wa_agendamento_confirmado_v1',
    name: 'WhatsApp Agendamento Confirmado',
    content: { templateKey: 'wa_agendamento_confirmado_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'whatsapp',
    stage: 'diagnostico_agendado',
    slug: 'wa_agendamento_conflito_reoferta_v1',
    name: 'WhatsApp Agendamento Conflito/Reoferta',
    content: { templateKey: 'wa_agendamento_conflito_reoferta_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'whatsapp',
    stage: 'diagnostico_agendado',
    slug: 'wa_agendamento_opcao_invalida_v1',
    name: 'WhatsApp Agendamento Opção Inválida',
    content: { templateKey: 'wa_agendamento_opcao_invalida_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'whatsapp',
    stage: 'diagnostico_agendado',
    slug: 'wa_briefing_recebido_agendamento_v1',
    name: 'WhatsApp Briefing Recebido + Agendamento',
    content: { templateKey: 'wa_briefing_recebido_agendamento_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'whatsapp',
    stage: 'diagnostico_agendado',
    slug: 'wa_reuniao_agendada_lembrete_v1',
    name: 'WhatsApp Lembrete Reunião',
    content: { templateKey: 'wa_reuniao_agendada_lembrete_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'whatsapp',
    stage: 'proposta_enviada',
    slug: 'wa_proposta_enviada_followup_v1',
    name: 'WhatsApp Followup Proposta',
    content: { templateKey: 'wa_proposta_enviada_followup_v1' },
    bindAsDefault: true,
  },
  {
    channel: 'whatsapp',
    stage: 'negociacao',
    slug: 'wa_negociacao_alinhamento_v1',
    name: 'WhatsApp Negociação',
    content: { templateKey: 'wa_negociacao_alinhamento_v1' },
    bindAsDefault: true,
  },
  {
    channel: 'whatsapp',
    stage: 'fechado',
    slug: 'wa_fechado_boas_vindas_v1',
    name: 'WhatsApp Boas-vindas Fechado',
    content: { templateKey: 'wa_fechado_boas_vindas_v1' },
    bindAsDefault: true,
  },
  {
    channel: 'gmail',
    stage: 'primeiro_contato',
    slug: 'gm_boas_vindas_comercial_v1',
    name: 'Gmail Primeiro Contato',
    content: { templateKey: 'gm_boas_vindas_comercial_v1' },
    bindAsDefault: true,
  },
  {
    channel: 'gmail',
    stage: 'diagnostico_agendado',
    slug: 'gm_briefing_recebido_agendamento_link_v1',
    name: 'Gmail Briefing Recebido + Link Agenda',
    content: { templateKey: 'gm_briefing_recebido_agendamento_link_v1' },
    bindAsDefault: true,
  },
  {
    channel: 'gmail',
    stage: 'diagnostico_agendado',
    slug: 'gm_briefing_recebido_agendamento_google_sugestoes_v1',
    name: 'Gmail Briefing Recebido + Sugestões Google',
    content: { templateKey: 'gm_briefing_recebido_agendamento_google_sugestoes_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'gmail',
    stage: 'diagnostico_agendado',
    slug: 'gm_briefing_recebido_agendamento_v1',
    name: 'Gmail Briefing Recebido + Agendamento',
    content: { templateKey: 'gm_briefing_recebido_agendamento_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'gmail',
    stage: 'diagnostico_agendado',
    slug: 'gm_reuniao_agendada_lembrete_v1',
    name: 'Gmail Lembrete Reunião',
    content: { templateKey: 'gm_reuniao_agendada_lembrete_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'gmail',
    stage: 'diagnostico_agendado',
    slug: 'gm_convite_reuniao_v1',
    name: 'Gmail Convite Reunião (Legado)',
    content: { templateKey: 'gm_convite_reuniao_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'gmail',
    stage: 'proposta_enviada',
    slug: 'gm_envio_proposta_v1',
    name: 'Gmail Envio Proposta',
    content: { templateKey: 'gm_envio_proposta_v1' },
    bindAsDefault: true,
  },
  {
    channel: 'gmail',
    stage: 'proposta_enviada',
    slug: 'gm_proposta_enviada_followup_v1',
    name: 'Gmail Followup Proposta',
    content: { templateKey: 'gm_proposta_enviada_followup_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'gmail',
    stage: 'negociacao',
    slug: 'gm_negociacao_alinhamento_v1',
    name: 'Gmail Negociação Alinhamento',
    content: { templateKey: 'gm_negociacao_alinhamento_v1' },
    bindAsDefault: true,
  },
  {
    channel: 'gmail',
    stage: 'negociacao',
    slug: 'gm_contraproposta_v1',
    name: 'Gmail Contraproposta (Legado)',
    content: { templateKey: 'gm_contraproposta_v1' },
    bindAsDefault: false,
  },
  {
    channel: 'gmail',
    stage: 'fechado',
    slug: 'gm_confirmacao_fechamento_v1',
    name: 'Gmail Confirmação Fechamento',
    content: { templateKey: 'gm_confirmacao_fechamento_v1' },
    bindAsDefault: true,
  },
];
