import type { OptimizationCenterPlaybook } from './types';

export const OPTIMIZATION_CENTER_PLAYBOOK_V1: OptimizationCenterPlaybook = {
  key: 'optimization-center',
  version: 'v1.2.0',
  updatedAt: '2026-02-04',
  description:
    'Playbook de otimização para campanhas de geração de demanda via Meta (WhatsApp/Mensagem), com regras por tema e guardrails de dados.',
  copy: {
    preferredCtaTypes: ['WHATSAPP_MESSAGE', 'SEND_MESSAGE'],
    prohibitedPhrases: ['garantido', '100%', 'resultado garantido', 'causa ganha', 'processo ganho'],
    notes: 'Regras de copy são heurísticas; ajustar conforme políticas da Meta e compliance do cliente.',
  },
  ai: {
    copySuggestions: {
      enabled: true,
      requiresEnv: 'OPENAI_API_KEY',
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
      promptVersion: 'copy-v1',
    },
  },
  defaults: {
    minSpendForEvaluation: 150,
    minContactsForEvaluation: 10,

    copyHeadlineMinChars: 18,
    copyHeadlineMaxChars: 60,
    copyPrimaryTextMaxChars: 220,

    targetCplGoodMax: 10,
    targetCplOkMax: 15,
    targetCplBadMin: 20,
    cplRisePctWarning: 40,
    contactsDropPctWarning: -50,

    frequencyWarning: 3,
    frequencyCritical: 5,
    firstReplyRateMin: 25,

    qualificationRateTargetMin: 12,

    creativeMinSpendWinner: 50,
    creativeMinSpendLoser: 200,
    creativeWinnerPercentile: 0.2,
    creativeWinnerMaxCount: 5,
    creativeLoserCplMultiplier: 2,
    creativeLoserMaxConversations: 3,
    creativeFatigueDropPct: -50,
    creativeFatigueCplMultiplier: 1.5,
    creativeFatigueMinPrevConversations: 10,
    creativeFatigueMinSpend: 100,

    hookRateMin: 15,
    holdRateMin: 25,
  },
  themes: [
    {
      key: 'trabalhista',
      name: 'Direito Trabalhista',
      description: 'Campanhas ligadas a direitos do trabalhador (demissão, rescisão, verbas, etc.).',
      tags: ['TRABALHISTA', 'TRABALHO'],
      keywords: ['trabalh', 'rescis', 'demiss', 'gestante', 'gravidez', 'verbas', 'fgts', 'salário', 'salario'],
      targets: {
        targetCplGoodMax: 12,
        targetCplOkMax: 18,
        targetCplBadMin: 25,
        qualificationRateTargetMin: 12,
        firstReplyRateMin: 28,
      },
    },
    {
      key: 'passageiro_aereo',
      name: 'Direito do Passageiro Aéreo',
      description: 'Atraso/cancelamento de voo, bagagem, overbooking, reembolso.',
      tags: ['PASSAGEIRO', 'AÉREO', 'AEREO', 'VOO'],
      keywords: ['passageiro', 'voo', 'aéreo', 'aereo', 'bagagem', 'overbooking', 'cancel', 'atras'],
      targets: {
        targetCplGoodMax: 9,
        targetCplOkMax: 14,
        targetCplBadMin: 20,
        qualificationRateTargetMin: 10,
        firstReplyRateMin: 25,
      },
    },
    {
      key: 'salario_maternidade',
      name: 'Salário Maternidade',
      description: 'Benefícios relacionados a maternidade e direitos de gestantes.',
      tags: ['MATERNIDADE', 'SALARIO_MATERNIDADE'],
      keywords: ['matern', 'salário maternidade', 'salario maternidade', 'gestante', 'gravidez'],
      targets: {
        targetCplGoodMax: 11,
        targetCplOkMax: 16,
        targetCplBadMin: 23,
        qualificationRateTargetMin: 14,
        firstReplyRateMin: 28,
      },
    },
    {
      key: 'geral',
      name: 'Geral',
      description: 'Fallback quando o tema não é detectado.',
      tags: [],
      keywords: [],
    },
  ],
  rules: [
    {
      id: 'data.no-creatives',
      level: 'data',
      severity: 'info',
      category: 'data',
      action: 'sync',
      title: 'Sem dados de criativos',
      description: 'Não há métricas de criativos no período.',
      condition: 'Nenhum registro em ad_creative_metrics no período (snapshot não capturado).',
    },
    {
      id: 'campaign.stalled',
      level: 'campaign',
      severity: 'warning',
      category: 'campaign',
      action: 'review',
      title: 'Campanha ativa sem entrega',
      description: 'Campanha marcada como ativa, mas sem impressões/gasto.',
      condition: 'status=active AND spend_total=0 AND impressions_total=0',
    },
    {
      id: 'campaign.no-contacts',
      level: 'campaign',
      severity: 'critical',
      category: 'campaign',
      action: 'refresh',
      title: 'Gasto sem gerar contatos',
      description: 'Gasto relevante e nenhum contato nos últimos 7 dias.',
      condition: 'spend_last7 >= minSpendForEvaluation AND contacts_last7 = 0',
    },
    {
      id: 'campaign.contacts-drop',
      level: 'campaign',
      severity: 'warning',
      category: 'campaign',
      action: 'refresh',
      title: 'Queda brusca de contatos',
      description: 'Queda relevante de contatos comparando 7d vs 7d anterior.',
      condition: 'contacts_prev7 >= minContactsForEvaluation AND delta_contacts_pct <= contactsDropPctWarning',
    },
    {
      id: 'campaign.cpl-rise',
      level: 'campaign',
      severity: 'warning',
      category: 'campaign',
      action: 'refresh',
      title: 'Custo por contato subiu',
      description: 'Custo por contato aumentou significativamente vs semana anterior.',
      condition: 'contacts_prev7 >= minContactsForEvaluation AND delta_cpl_pct >= cplRisePctWarning',
    },
    {
      id: 'campaign.cpl-above-ok',
      level: 'campaign',
      severity: 'warning',
      category: 'campaign',
      action: 'refresh',
      title: 'CPL acima do desejado (tema)',
      description: 'CPL acima do desejado para o tema detectado.',
      condition: 'cpl_last7 > targetCplOkMax AND cpl_last7 < targetCplBadMin',
    },
    {
      id: 'campaign.cpl-high',
      level: 'campaign',
      severity: 'critical',
      category: 'campaign',
      action: 'refresh',
      title: 'CPL acima do ideal (tema)',
      description: 'CPL acima do limite do tema (alto risco de ineficiência).',
      condition: 'cpl_last7 >= targetCplBadMin',
    },
    {
      id: 'campaign.frequency-high',
      level: 'campaign',
      severity: 'warning',
      category: 'campaign',
      action: 'refresh',
      title: 'Frequência alta (saturação)',
      description: 'Frequência elevada sugere fadiga de criativo e público pequeno.',
      condition: 'avg_frequency_last7 >= frequencyWarning',
    },
    {
      id: 'campaign.first-reply-low',
      level: 'campaign',
      severity: 'warning',
      category: 'campaign',
      action: 'review',
      title: 'Baixa taxa de primeira resposta',
      description: 'Muitas conversas iniciadas, mas pouca primeira resposta do usuário.',
      condition: 'conversations_last7 >= minContactsForEvaluation AND first_reply_rate < firstReplyRateMin',
    },
    {
      id: 'campaign.scale-opportunity',
      level: 'campaign',
      severity: 'opportunity',
      category: 'campaign',
      action: 'scale',
      title: 'Oportunidade de escalar',
      description: 'Campanha está saudável (CPL bom) e com tendência positiva.',
      condition: 'cpl_last7 <= targetCplGoodMax AND (delta_contacts_pct >= 20 OR delta_cpl_pct <= -20)',
    },
    {
      id: 'qualification.missing',
      level: 'qualification',
      severity: 'info',
      category: 'qualification',
      action: 'track',
      title: 'Sem dados de qualificação',
      description: 'Há contatos, mas não há registros de qualificação manual.',
      condition: 'contacts_last7 > 0 AND spend_last7 > minSpendForEvaluation AND tracking_records_last7 = 0',
    },
    {
      id: 'qualification.zero',
      level: 'qualification',
      severity: 'critical',
      category: 'qualification',
      action: 'review',
      title: 'Contatos sem qualificados',
      description: 'Há gasto e contatos, mas nenhum qualificado no período.',
      condition: 'spend_last7 > minSpendForEvaluation AND contacts_last7 > 0 AND qualified_last7 = 0',
    },
    {
      id: 'qualification.low',
      level: 'qualification',
      severity: 'warning',
      category: 'qualification',
      action: 'review',
      title: 'Qualificação baixa',
      description: 'Percentual de qualificados abaixo da meta do tema.',
      condition: 'tracking_records_last7 > 0 AND qualification_rate < qualificationRateTargetMin',
    },
    {
      id: 'creative.loser',
      level: 'creative',
      severity: 'warning',
      category: 'creative',
      action: 'pause',
      title: 'Criativo com baixo desempenho',
      description: 'Alto gasto com pouco/nenhum resultado de conversas.',
      condition: 'spend_total >= creativeMinSpendLoser AND (conversations_total=0 OR cpl >= median_cpl * creativeLoserCplMultiplier)',
    },
    {
      id: 'creative.fatigued',
      level: 'creative',
      severity: 'warning',
      category: 'creative',
      action: 'refresh',
      title: 'Sinal de fadiga de criativo',
      description: 'Perda de performance comparando últimos 7 dias vs 7 dias anteriores.',
      condition: 'conversations_prev7 >= creativeFatigueMinPrevConversations AND delta_contacts_pct <= creativeFatigueDropPct',
    },
    {
      id: 'creative.winner',
      level: 'creative',
      severity: 'opportunity',
      category: 'creative',
      action: 'scale',
      title: 'Criativo vencedor',
      description: 'Criativo no topo do período e com CPL dentro do alvo do tema.',
      condition: 'eligible AND rank_in_top_percentile AND cpl <= targetCplGoodMax AND NOT fatigued',
    },
    {
      id: 'creative.video-hook-low',
      level: 'creative',
      severity: 'warning',
      category: 'creative',
      action: 'refresh',
      title: 'Hook baixo (vídeo)',
      description: 'Hook rate abaixo do mínimo sugerido no playbook.',
      condition: 'is_video AND spend_total >= creativeMinSpendWinner AND hook_rate_avg < hookRateMin',
    },
    {
      id: 'creative.video-hold-low',
      level: 'creative',
      severity: 'info',
      category: 'creative',
      action: 'refresh',
      title: 'Hold baixo (vídeo)',
      description: 'Hold rate abaixo do mínimo sugerido; otimizar narrativa e ritmo.',
      condition: 'is_video AND spend_total >= creativeMinSpendWinner AND hold_rate_avg < holdRateMin',
    },
    {
      id: 'creative.copy-insights-missing',
      level: 'creative',
      severity: 'info',
      category: 'creative',
      action: 'review',
      title: 'Sem insights de copy',
      description: 'Ainda não há análise de copy para este criativo (título/texto/CTA). Gere sugestões para acelerar a otimização.',
      condition: 'highlighted_creative AND no row in creative_copy_insights for snapshot',
    },
    {
      id: 'creative.copy-missing-headline',
      level: 'creative',
      severity: 'warning',
      category: 'creative',
      action: 'refresh',
      title: 'Criativo sem título (headline)',
      description: 'O snapshot não possui headline (título). Isso dificulta comparar variações e otimizar copy.',
      condition: 'headline is null/empty (and dynamic headlines missing)',
    },
    {
      id: 'creative.copy-headline-length',
      level: 'creative',
      severity: 'info',
      category: 'creative',
      action: 'refresh',
      title: 'Título fora do recomendado',
      description: 'Headline muito curto/long. Ajuste para melhorar clareza e impacto.',
      condition: 'headline_length < copyHeadlineMinChars OR headline_length > copyHeadlineMaxChars',
    },
    {
      id: 'creative.copy-primary-too-long',
      level: 'creative',
      severity: 'info',
      category: 'creative',
      action: 'refresh',
      title: 'Texto principal muito longo',
      description: 'Texto principal acima do recomendado. Prefira frases curtas e diretas para gerar conversas no WhatsApp.',
      condition: 'primary_text_length > copyPrimaryTextMaxChars',
    },
    {
      id: 'creative.copy-cta-mismatch',
      level: 'creative',
      severity: 'warning',
      category: 'creative',
      action: 'refresh',
      title: 'CTA pouco compatível com conversa',
      description: 'CTA não é WhatsApp/Mensagem. Isso pode reduzir conversas iniciadas.',
      condition: 'cta_type not in preferredCtaTypes',
    },
    {
      id: 'creative.copy-theme-not-mentioned',
      level: 'creative',
      severity: 'info',
      category: 'creative',
      action: 'refresh',
      title: 'Copy não cita o tema',
      description: 'O texto não contém termos do tema detectado. Considere explicitar o assunto para aumentar qualificação.',
      condition: 'theme != geral AND inferred_theme_from_copy = geral',
    },
    {
      id: 'creative.copy-compliance-risk',
      level: 'creative',
      severity: 'warning',
      category: 'creative',
      action: 'review',
      title: 'Risco de promessa (copy)',
      description: 'Copy contém termos de promessa absoluta (ex.: “garantido”, “100%”). Ajuste para reduzir risco e reprovação.',
      condition: 'copy contains prohibited phrase',
    },
  ],
};
