import { FastifyPluginAsync } from 'fastify';
import breakdownsRoutes from './analytics/breakdowns.routes';
import businessMetricsRoutes from './analytics/business-metrics.routes';
import campaignCreativeMetricsRoutes from './analytics/campaign-creative-metrics.routes';
import copyInsightsRoutes from './analytics/copy-insights.routes';
import creativeLibraryRoutes from './analytics/creative-library.routes';
import creativeSnapshotsRoutes from './analytics/creative-snapshots.routes';
import actionProposalsRoutes from './analytics/action-proposals.routes';
import optimizationCenterRoutes from './analytics/optimization-center.routes';
import playbookRoutes from './analytics/playbooks.routes';
import temporalAnalysisRoutes from './analytics/temporal-analysis.routes';
import budgetPacingRoutes from './analytics/budget-pacing.routes';
import creativeWinnersRoutes from './analytics/creative-winners.routes';
import copyGeneratorRoutes from './analytics/copy-generator.routes';
import audienceInsightsRoutes from './analytics/audience-insights.routes';
import anomalyDetectionRoutes from './analytics/anomaly-detection.routes';
import campaignHealthRoutes from './analytics/campaign-health.routes';
import weeklySummaryRoutes from './analytics/weekly-summary.routes';
import { authenticate } from '../middleware/auth';

const analyticsRoutes: FastifyPluginAsync = async (fastify) => {
  fastify.addHook('preHandler', authenticate);
  fastify.register(playbookRoutes);
  fastify.register(copyInsightsRoutes);
  fastify.register(campaignCreativeMetricsRoutes);
  fastify.register(creativeLibraryRoutes);
  fastify.register(creativeSnapshotsRoutes);
  fastify.register(actionProposalsRoutes);
  fastify.register(breakdownsRoutes);
  fastify.register(temporalAnalysisRoutes);
  fastify.register(businessMetricsRoutes);
  fastify.register(optimizationCenterRoutes);
  fastify.register(budgetPacingRoutes);
  fastify.register(creativeWinnersRoutes);
  fastify.register(copyGeneratorRoutes);
  fastify.register(audienceInsightsRoutes);
  fastify.register(anomalyDetectionRoutes);
  fastify.register(campaignHealthRoutes);
  fastify.register(weeklySummaryRoutes);
};

export default analyticsRoutes;
